#!/bin/sh

set -eu

info()    { printf "\\e[32m[INFO]\\e[0m    %s\\n" "$*" >&2 ; }
warning() { printf "\\e[33m[WARNING]\\e[0m %s\\n" "$*" >&2 ; }
error()   { printf "\\e[31m[ERROR]\\e[0m   %s\\n" "$*" >&2 ; }
fatal()   { printf "\\e[35m[FATAL]\\e[0m   %s\\n" "$*" >&2 ; exit 1 ; }

if [ "$#" -ne 2 ]; then
    fatal "usage: $(basename "${0}") host port"
fi

if ! command -v socat >/dev/null 2>&1; then
    fatal "command not found: socat"
fi

HOST="$1"
PORT="$2"

LISTEN_PORT=${LISTEN_PORT:-${PORT}}

info "relay TCP/IP connections on :${LISTEN_PORT} to ${HOST}:${PORT}"
exec socat "TCP-LISTEN:${LISTEN_PORT},fork,reuseaddr" "TCP:${HOST}:${PORT}"
